// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: keeper.proto

package keeper

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Keeper_Registration_FullMethodName       = "/keeper_proto.Keeper/registration"
	Keeper_Login_FullMethodName              = "/keeper_proto.Keeper/login"
	Keeper_AddCredentials_FullMethodName     = "/keeper_proto.Keeper/addCredentials"
	Keeper_GetCredentialsList_FullMethodName = "/keeper_proto.Keeper/getCredentialsList"
	Keeper_DeleteCredential_FullMethodName   = "/keeper_proto.Keeper/deleteCredential"
	Keeper_UpdateCredentials_FullMethodName  = "/keeper_proto.Keeper/updateCredentials"
	Keeper_UploadBinaryFile_FullMethodName   = "/keeper_proto.Keeper/uploadBinaryFile"
	Keeper_GetBinaryFileList_FullMethodName  = "/keeper_proto.Keeper/getBinaryFileList"
	Keeper_DownloadBinaryFile_FullMethodName = "/keeper_proto.Keeper/downloadBinaryFile"
	Keeper_UpdateBinaryFile_FullMethodName   = "/keeper_proto.Keeper/updateBinaryFile"
	Keeper_DeleteBinaryFile_FullMethodName   = "/keeper_proto.Keeper/deleteBinaryFile"
	Keeper_UploadTextFile_FullMethodName     = "/keeper_proto.Keeper/uploadTextFile"
	Keeper_GetTextList_FullMethodName        = "/keeper_proto.Keeper/getTextList"
	Keeper_UploadText_FullMethodName         = "/keeper_proto.Keeper/uploadText"
	Keeper_DeleteText_FullMethodName         = "/keeper_proto.Keeper/deleteText"
	Keeper_UpdateText_FullMethodName         = "/keeper_proto.Keeper/updateText"
	Keeper_UpdateTextFile_FullMethodName     = "/keeper_proto.Keeper/updateTextFile"
	Keeper_AddCreditCard_FullMethodName      = "/keeper_proto.Keeper/addCreditCard"
	Keeper_GetCreditCardList_FullMethodName  = "/keeper_proto.Keeper/getCreditCardList"
	Keeper_UpdateCreditCard_FullMethodName   = "/keeper_proto.Keeper/updateCreditCard"
	Keeper_DeleteCreditCard_FullMethodName   = "/keeper_proto.Keeper/deleteCreditCard"
)

// KeeperClient is the client API for Keeper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KeeperClient interface {
	Registration(ctx context.Context, in *NewUserRequest, opts ...grpc.CallOption) (*NewUserResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	AddCredentials(ctx context.Context, in *AddCredentialsRequest, opts ...grpc.CallOption) (*AddCredentialsResponse, error)
	GetCredentialsList(ctx context.Context, in *CredentialListRequest, opts ...grpc.CallOption) (*CredentialListResponse, error)
	DeleteCredential(ctx context.Context, in *DeleteCredentialRequest, opts ...grpc.CallOption) (*DeleteCredentialResponse, error)
	UpdateCredentials(ctx context.Context, in *UpdateCredentialsRequest, opts ...grpc.CallOption) (*UpdateCredentialsResponse, error)
	UploadBinaryFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadBinaryFileRequest, UploadBinaryFileResponse], error)
	GetBinaryFileList(ctx context.Context, in *BinaryFileListRequest, opts ...grpc.CallOption) (*BinaryFileListResponse, error)
	DownloadBinaryFile(ctx context.Context, in *DownloadBinaryFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadBinaryFileResponse], error)
	UpdateBinaryFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UpdateBinaryFileRequest, UpdateBinaryFileResponse], error)
	DeleteBinaryFile(ctx context.Context, in *DeleteBinaryFileRequest, opts ...grpc.CallOption) (*DeleteBinaryFileResponse, error)
	UploadTextFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadTextFileRequest, UploadTextFileResponse], error)
	GetTextList(ctx context.Context, in *TextListRequest, opts ...grpc.CallOption) (*TextListResponse, error)
	UploadText(ctx context.Context, in *UploadTextRequest, opts ...grpc.CallOption) (*UploadTextResponse, error)
	DeleteText(ctx context.Context, in *DeleteTextRequest, opts ...grpc.CallOption) (*DeleteTextResponse, error)
	UpdateText(ctx context.Context, in *UpdateTextRequest, opts ...grpc.CallOption) (*UpdateTextResponse, error)
	UpdateTextFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UpdateTextFileRequest, UpdateTextFileResponse], error)
	AddCreditCard(ctx context.Context, in *AddCreditCardRequest, opts ...grpc.CallOption) (*AddCreditCardResponse, error)
	GetCreditCardList(ctx context.Context, in *CreditCardRequest, opts ...grpc.CallOption) (*CreditCardListResponse, error)
	UpdateCreditCard(ctx context.Context, in *UpdateCreditCardRequest, opts ...grpc.CallOption) (*UpdateCreditCardResponse, error)
	DeleteCreditCard(ctx context.Context, in *DeleteCreditCardRequest, opts ...grpc.CallOption) (*DeleteCreditCardResponse, error)
}

type keeperClient struct {
	cc grpc.ClientConnInterface
}

func NewKeeperClient(cc grpc.ClientConnInterface) KeeperClient {
	return &keeperClient{cc}
}

func (c *keeperClient) Registration(ctx context.Context, in *NewUserRequest, opts ...grpc.CallOption) (*NewUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewUserResponse)
	err := c.cc.Invoke(ctx, Keeper_Registration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keeperClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, Keeper_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keeperClient) AddCredentials(ctx context.Context, in *AddCredentialsRequest, opts ...grpc.CallOption) (*AddCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddCredentialsResponse)
	err := c.cc.Invoke(ctx, Keeper_AddCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keeperClient) GetCredentialsList(ctx context.Context, in *CredentialListRequest, opts ...grpc.CallOption) (*CredentialListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CredentialListResponse)
	err := c.cc.Invoke(ctx, Keeper_GetCredentialsList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keeperClient) DeleteCredential(ctx context.Context, in *DeleteCredentialRequest, opts ...grpc.CallOption) (*DeleteCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCredentialResponse)
	err := c.cc.Invoke(ctx, Keeper_DeleteCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keeperClient) UpdateCredentials(ctx context.Context, in *UpdateCredentialsRequest, opts ...grpc.CallOption) (*UpdateCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCredentialsResponse)
	err := c.cc.Invoke(ctx, Keeper_UpdateCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keeperClient) UploadBinaryFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadBinaryFileRequest, UploadBinaryFileResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Keeper_ServiceDesc.Streams[0], Keeper_UploadBinaryFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadBinaryFileRequest, UploadBinaryFileResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Keeper_UploadBinaryFileClient = grpc.ClientStreamingClient[UploadBinaryFileRequest, UploadBinaryFileResponse]

func (c *keeperClient) GetBinaryFileList(ctx context.Context, in *BinaryFileListRequest, opts ...grpc.CallOption) (*BinaryFileListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BinaryFileListResponse)
	err := c.cc.Invoke(ctx, Keeper_GetBinaryFileList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keeperClient) DownloadBinaryFile(ctx context.Context, in *DownloadBinaryFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadBinaryFileResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Keeper_ServiceDesc.Streams[1], Keeper_DownloadBinaryFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadBinaryFileRequest, DownloadBinaryFileResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Keeper_DownloadBinaryFileClient = grpc.ServerStreamingClient[DownloadBinaryFileResponse]

func (c *keeperClient) UpdateBinaryFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UpdateBinaryFileRequest, UpdateBinaryFileResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Keeper_ServiceDesc.Streams[2], Keeper_UpdateBinaryFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UpdateBinaryFileRequest, UpdateBinaryFileResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Keeper_UpdateBinaryFileClient = grpc.ClientStreamingClient[UpdateBinaryFileRequest, UpdateBinaryFileResponse]

func (c *keeperClient) DeleteBinaryFile(ctx context.Context, in *DeleteBinaryFileRequest, opts ...grpc.CallOption) (*DeleteBinaryFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBinaryFileResponse)
	err := c.cc.Invoke(ctx, Keeper_DeleteBinaryFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keeperClient) UploadTextFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadTextFileRequest, UploadTextFileResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Keeper_ServiceDesc.Streams[3], Keeper_UploadTextFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadTextFileRequest, UploadTextFileResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Keeper_UploadTextFileClient = grpc.ClientStreamingClient[UploadTextFileRequest, UploadTextFileResponse]

func (c *keeperClient) GetTextList(ctx context.Context, in *TextListRequest, opts ...grpc.CallOption) (*TextListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TextListResponse)
	err := c.cc.Invoke(ctx, Keeper_GetTextList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keeperClient) UploadText(ctx context.Context, in *UploadTextRequest, opts ...grpc.CallOption) (*UploadTextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadTextResponse)
	err := c.cc.Invoke(ctx, Keeper_UploadText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keeperClient) DeleteText(ctx context.Context, in *DeleteTextRequest, opts ...grpc.CallOption) (*DeleteTextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTextResponse)
	err := c.cc.Invoke(ctx, Keeper_DeleteText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keeperClient) UpdateText(ctx context.Context, in *UpdateTextRequest, opts ...grpc.CallOption) (*UpdateTextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTextResponse)
	err := c.cc.Invoke(ctx, Keeper_UpdateText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keeperClient) UpdateTextFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UpdateTextFileRequest, UpdateTextFileResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Keeper_ServiceDesc.Streams[4], Keeper_UpdateTextFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UpdateTextFileRequest, UpdateTextFileResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Keeper_UpdateTextFileClient = grpc.ClientStreamingClient[UpdateTextFileRequest, UpdateTextFileResponse]

func (c *keeperClient) AddCreditCard(ctx context.Context, in *AddCreditCardRequest, opts ...grpc.CallOption) (*AddCreditCardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddCreditCardResponse)
	err := c.cc.Invoke(ctx, Keeper_AddCreditCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keeperClient) GetCreditCardList(ctx context.Context, in *CreditCardRequest, opts ...grpc.CallOption) (*CreditCardListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreditCardListResponse)
	err := c.cc.Invoke(ctx, Keeper_GetCreditCardList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keeperClient) UpdateCreditCard(ctx context.Context, in *UpdateCreditCardRequest, opts ...grpc.CallOption) (*UpdateCreditCardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCreditCardResponse)
	err := c.cc.Invoke(ctx, Keeper_UpdateCreditCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keeperClient) DeleteCreditCard(ctx context.Context, in *DeleteCreditCardRequest, opts ...grpc.CallOption) (*DeleteCreditCardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCreditCardResponse)
	err := c.cc.Invoke(ctx, Keeper_DeleteCreditCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeeperServer is the server API for Keeper service.
// All implementations must embed UnimplementedKeeperServer
// for forward compatibility.
type KeeperServer interface {
	Registration(context.Context, *NewUserRequest) (*NewUserResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	AddCredentials(context.Context, *AddCredentialsRequest) (*AddCredentialsResponse, error)
	GetCredentialsList(context.Context, *CredentialListRequest) (*CredentialListResponse, error)
	DeleteCredential(context.Context, *DeleteCredentialRequest) (*DeleteCredentialResponse, error)
	UpdateCredentials(context.Context, *UpdateCredentialsRequest) (*UpdateCredentialsResponse, error)
	UploadBinaryFile(grpc.ClientStreamingServer[UploadBinaryFileRequest, UploadBinaryFileResponse]) error
	GetBinaryFileList(context.Context, *BinaryFileListRequest) (*BinaryFileListResponse, error)
	DownloadBinaryFile(*DownloadBinaryFileRequest, grpc.ServerStreamingServer[DownloadBinaryFileResponse]) error
	UpdateBinaryFile(grpc.ClientStreamingServer[UpdateBinaryFileRequest, UpdateBinaryFileResponse]) error
	DeleteBinaryFile(context.Context, *DeleteBinaryFileRequest) (*DeleteBinaryFileResponse, error)
	UploadTextFile(grpc.ClientStreamingServer[UploadTextFileRequest, UploadTextFileResponse]) error
	GetTextList(context.Context, *TextListRequest) (*TextListResponse, error)
	UploadText(context.Context, *UploadTextRequest) (*UploadTextResponse, error)
	DeleteText(context.Context, *DeleteTextRequest) (*DeleteTextResponse, error)
	UpdateText(context.Context, *UpdateTextRequest) (*UpdateTextResponse, error)
	UpdateTextFile(grpc.ClientStreamingServer[UpdateTextFileRequest, UpdateTextFileResponse]) error
	AddCreditCard(context.Context, *AddCreditCardRequest) (*AddCreditCardResponse, error)
	GetCreditCardList(context.Context, *CreditCardRequest) (*CreditCardListResponse, error)
	UpdateCreditCard(context.Context, *UpdateCreditCardRequest) (*UpdateCreditCardResponse, error)
	DeleteCreditCard(context.Context, *DeleteCreditCardRequest) (*DeleteCreditCardResponse, error)
	mustEmbedUnimplementedKeeperServer()
}

// UnimplementedKeeperServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKeeperServer struct{}

func (UnimplementedKeeperServer) Registration(context.Context, *NewUserRequest) (*NewUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Registration not implemented")
}
func (UnimplementedKeeperServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedKeeperServer) AddCredentials(context.Context, *AddCredentialsRequest) (*AddCredentialsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCredentials not implemented")
}
func (UnimplementedKeeperServer) GetCredentialsList(context.Context, *CredentialListRequest) (*CredentialListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCredentialsList not implemented")
}
func (UnimplementedKeeperServer) DeleteCredential(context.Context, *DeleteCredentialRequest) (*DeleteCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCredential not implemented")
}
func (UnimplementedKeeperServer) UpdateCredentials(context.Context, *UpdateCredentialsRequest) (*UpdateCredentialsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCredentials not implemented")
}
func (UnimplementedKeeperServer) UploadBinaryFile(grpc.ClientStreamingServer[UploadBinaryFileRequest, UploadBinaryFileResponse]) error {
	return status.Errorf(codes.Unimplemented, "method UploadBinaryFile not implemented")
}
func (UnimplementedKeeperServer) GetBinaryFileList(context.Context, *BinaryFileListRequest) (*BinaryFileListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBinaryFileList not implemented")
}
func (UnimplementedKeeperServer) DownloadBinaryFile(*DownloadBinaryFileRequest, grpc.ServerStreamingServer[DownloadBinaryFileResponse]) error {
	return status.Errorf(codes.Unimplemented, "method DownloadBinaryFile not implemented")
}
func (UnimplementedKeeperServer) UpdateBinaryFile(grpc.ClientStreamingServer[UpdateBinaryFileRequest, UpdateBinaryFileResponse]) error {
	return status.Errorf(codes.Unimplemented, "method UpdateBinaryFile not implemented")
}
func (UnimplementedKeeperServer) DeleteBinaryFile(context.Context, *DeleteBinaryFileRequest) (*DeleteBinaryFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBinaryFile not implemented")
}
func (UnimplementedKeeperServer) UploadTextFile(grpc.ClientStreamingServer[UploadTextFileRequest, UploadTextFileResponse]) error {
	return status.Errorf(codes.Unimplemented, "method UploadTextFile not implemented")
}
func (UnimplementedKeeperServer) GetTextList(context.Context, *TextListRequest) (*TextListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTextList not implemented")
}
func (UnimplementedKeeperServer) UploadText(context.Context, *UploadTextRequest) (*UploadTextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadText not implemented")
}
func (UnimplementedKeeperServer) DeleteText(context.Context, *DeleteTextRequest) (*DeleteTextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteText not implemented")
}
func (UnimplementedKeeperServer) UpdateText(context.Context, *UpdateTextRequest) (*UpdateTextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateText not implemented")
}
func (UnimplementedKeeperServer) UpdateTextFile(grpc.ClientStreamingServer[UpdateTextFileRequest, UpdateTextFileResponse]) error {
	return status.Errorf(codes.Unimplemented, "method UpdateTextFile not implemented")
}
func (UnimplementedKeeperServer) AddCreditCard(context.Context, *AddCreditCardRequest) (*AddCreditCardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCreditCard not implemented")
}
func (UnimplementedKeeperServer) GetCreditCardList(context.Context, *CreditCardRequest) (*CreditCardListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCreditCardList not implemented")
}
func (UnimplementedKeeperServer) UpdateCreditCard(context.Context, *UpdateCreditCardRequest) (*UpdateCreditCardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCreditCard not implemented")
}
func (UnimplementedKeeperServer) DeleteCreditCard(context.Context, *DeleteCreditCardRequest) (*DeleteCreditCardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCreditCard not implemented")
}
func (UnimplementedKeeperServer) mustEmbedUnimplementedKeeperServer() {}
func (UnimplementedKeeperServer) testEmbeddedByValue()                {}

// UnsafeKeeperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeeperServer will
// result in compilation errors.
type UnsafeKeeperServer interface {
	mustEmbedUnimplementedKeeperServer()
}

func RegisterKeeperServer(s grpc.ServiceRegistrar, srv KeeperServer) {
	// If the following call pancis, it indicates UnimplementedKeeperServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Keeper_ServiceDesc, srv)
}

func _Keeper_Registration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperServer).Registration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Keeper_Registration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperServer).Registration(ctx, req.(*NewUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Keeper_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Keeper_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Keeper_AddCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperServer).AddCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Keeper_AddCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperServer).AddCredentials(ctx, req.(*AddCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Keeper_GetCredentialsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CredentialListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperServer).GetCredentialsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Keeper_GetCredentialsList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperServer).GetCredentialsList(ctx, req.(*CredentialListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Keeper_DeleteCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperServer).DeleteCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Keeper_DeleteCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperServer).DeleteCredential(ctx, req.(*DeleteCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Keeper_UpdateCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperServer).UpdateCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Keeper_UpdateCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperServer).UpdateCredentials(ctx, req.(*UpdateCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Keeper_UploadBinaryFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(KeeperServer).UploadBinaryFile(&grpc.GenericServerStream[UploadBinaryFileRequest, UploadBinaryFileResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Keeper_UploadBinaryFileServer = grpc.ClientStreamingServer[UploadBinaryFileRequest, UploadBinaryFileResponse]

func _Keeper_GetBinaryFileList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BinaryFileListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperServer).GetBinaryFileList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Keeper_GetBinaryFileList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperServer).GetBinaryFileList(ctx, req.(*BinaryFileListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Keeper_DownloadBinaryFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadBinaryFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KeeperServer).DownloadBinaryFile(m, &grpc.GenericServerStream[DownloadBinaryFileRequest, DownloadBinaryFileResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Keeper_DownloadBinaryFileServer = grpc.ServerStreamingServer[DownloadBinaryFileResponse]

func _Keeper_UpdateBinaryFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(KeeperServer).UpdateBinaryFile(&grpc.GenericServerStream[UpdateBinaryFileRequest, UpdateBinaryFileResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Keeper_UpdateBinaryFileServer = grpc.ClientStreamingServer[UpdateBinaryFileRequest, UpdateBinaryFileResponse]

func _Keeper_DeleteBinaryFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBinaryFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperServer).DeleteBinaryFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Keeper_DeleteBinaryFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperServer).DeleteBinaryFile(ctx, req.(*DeleteBinaryFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Keeper_UploadTextFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(KeeperServer).UploadTextFile(&grpc.GenericServerStream[UploadTextFileRequest, UploadTextFileResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Keeper_UploadTextFileServer = grpc.ClientStreamingServer[UploadTextFileRequest, UploadTextFileResponse]

func _Keeper_GetTextList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperServer).GetTextList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Keeper_GetTextList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperServer).GetTextList(ctx, req.(*TextListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Keeper_UploadText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperServer).UploadText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Keeper_UploadText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperServer).UploadText(ctx, req.(*UploadTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Keeper_DeleteText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperServer).DeleteText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Keeper_DeleteText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperServer).DeleteText(ctx, req.(*DeleteTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Keeper_UpdateText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperServer).UpdateText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Keeper_UpdateText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperServer).UpdateText(ctx, req.(*UpdateTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Keeper_UpdateTextFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(KeeperServer).UpdateTextFile(&grpc.GenericServerStream[UpdateTextFileRequest, UpdateTextFileResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Keeper_UpdateTextFileServer = grpc.ClientStreamingServer[UpdateTextFileRequest, UpdateTextFileResponse]

func _Keeper_AddCreditCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCreditCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperServer).AddCreditCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Keeper_AddCreditCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperServer).AddCreditCard(ctx, req.(*AddCreditCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Keeper_GetCreditCardList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreditCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperServer).GetCreditCardList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Keeper_GetCreditCardList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperServer).GetCreditCardList(ctx, req.(*CreditCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Keeper_UpdateCreditCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCreditCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperServer).UpdateCreditCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Keeper_UpdateCreditCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperServer).UpdateCreditCard(ctx, req.(*UpdateCreditCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Keeper_DeleteCreditCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCreditCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeeperServer).DeleteCreditCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Keeper_DeleteCreditCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeeperServer).DeleteCreditCard(ctx, req.(*DeleteCreditCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Keeper_ServiceDesc is the grpc.ServiceDesc for Keeper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Keeper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "keeper_proto.Keeper",
	HandlerType: (*KeeperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "registration",
			Handler:    _Keeper_Registration_Handler,
		},
		{
			MethodName: "login",
			Handler:    _Keeper_Login_Handler,
		},
		{
			MethodName: "addCredentials",
			Handler:    _Keeper_AddCredentials_Handler,
		},
		{
			MethodName: "getCredentialsList",
			Handler:    _Keeper_GetCredentialsList_Handler,
		},
		{
			MethodName: "deleteCredential",
			Handler:    _Keeper_DeleteCredential_Handler,
		},
		{
			MethodName: "updateCredentials",
			Handler:    _Keeper_UpdateCredentials_Handler,
		},
		{
			MethodName: "getBinaryFileList",
			Handler:    _Keeper_GetBinaryFileList_Handler,
		},
		{
			MethodName: "deleteBinaryFile",
			Handler:    _Keeper_DeleteBinaryFile_Handler,
		},
		{
			MethodName: "getTextList",
			Handler:    _Keeper_GetTextList_Handler,
		},
		{
			MethodName: "uploadText",
			Handler:    _Keeper_UploadText_Handler,
		},
		{
			MethodName: "deleteText",
			Handler:    _Keeper_DeleteText_Handler,
		},
		{
			MethodName: "updateText",
			Handler:    _Keeper_UpdateText_Handler,
		},
		{
			MethodName: "addCreditCard",
			Handler:    _Keeper_AddCreditCard_Handler,
		},
		{
			MethodName: "getCreditCardList",
			Handler:    _Keeper_GetCreditCardList_Handler,
		},
		{
			MethodName: "updateCreditCard",
			Handler:    _Keeper_UpdateCreditCard_Handler,
		},
		{
			MethodName: "deleteCreditCard",
			Handler:    _Keeper_DeleteCreditCard_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "uploadBinaryFile",
			Handler:       _Keeper_UploadBinaryFile_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "downloadBinaryFile",
			Handler:       _Keeper_DownloadBinaryFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "updateBinaryFile",
			Handler:       _Keeper_UpdateBinaryFile_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "uploadTextFile",
			Handler:       _Keeper_UploadTextFile_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "updateTextFile",
			Handler:       _Keeper_UpdateTextFile_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "keeper.proto",
}
