// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: proto/keeper.proto

package keeper

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewUserRequest) Reset() {
	*x = NewUserRequest{}
	mi := &file_proto_keeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewUserRequest) ProtoMessage() {}

func (x *NewUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewUserRequest.ProtoReflect.Descriptor instead.
func (*NewUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{0}
}

func (x *NewUserRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *NewUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type NewUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewUserResponse) Reset() {
	*x = NewUserResponse{}
	mi := &file_proto_keeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewUserResponse) ProtoMessage() {}

func (x *NewUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewUserResponse.ProtoReflect.Descriptor instead.
func (*NewUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{1}
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_keeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_keeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AddCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCredentialsRequest) Reset() {
	*x = AddCredentialsRequest{}
	mi := &file_proto_keeper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCredentialsRequest) ProtoMessage() {}

func (x *AddCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCredentialsRequest.ProtoReflect.Descriptor instead.
func (*AddCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{4}
}

func (x *AddCredentialsRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *AddCredentialsRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AddCredentialsRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type AddCredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCredentialsResponse) Reset() {
	*x = AddCredentialsResponse{}
	mi := &file_proto_keeper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCredentialsResponse) ProtoMessage() {}

func (x *AddCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCredentialsResponse.ProtoReflect.Descriptor instead.
func (*AddCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{5}
}

type Credential struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Id            uint32                 `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Credential) Reset() {
	*x = Credential{}
	mi := &file_proto_keeper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credential) ProtoMessage() {}

func (x *Credential) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credential.ProtoReflect.Descriptor instead.
func (*Credential) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{6}
}

func (x *Credential) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *Credential) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Credential) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Credential) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CredentialListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialListRequest) Reset() {
	*x = CredentialListRequest{}
	mi := &file_proto_keeper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialListRequest) ProtoMessage() {}

func (x *CredentialListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialListRequest.ProtoReflect.Descriptor instead.
func (*CredentialListRequest) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{7}
}

type CredentialListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credentials   []*Credential          `protobuf:"bytes,1,rep,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialListResponse) Reset() {
	*x = CredentialListResponse{}
	mi := &file_proto_keeper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialListResponse) ProtoMessage() {}

func (x *CredentialListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialListResponse.ProtoReflect.Descriptor instead.
func (*CredentialListResponse) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{8}
}

func (x *CredentialListResponse) GetCredentials() []*Credential {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type DeleteCredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCredentialRequest) Reset() {
	*x = DeleteCredentialRequest{}
	mi := &file_proto_keeper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCredentialRequest) ProtoMessage() {}

func (x *DeleteCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCredentialRequest.ProtoReflect.Descriptor instead.
func (*DeleteCredentialRequest) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteCredentialRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteCredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCredentialResponse) Reset() {
	*x = DeleteCredentialResponse{}
	mi := &file_proto_keeper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCredentialResponse) ProtoMessage() {}

func (x *DeleteCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCredentialResponse.ProtoReflect.Descriptor instead.
func (*DeleteCredentialResponse) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{10}
}

type UploadBinaryFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadBinaryFileRequest) Reset() {
	*x = UploadBinaryFileRequest{}
	mi := &file_proto_keeper_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadBinaryFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadBinaryFileRequest) ProtoMessage() {}

func (x *UploadBinaryFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadBinaryFileRequest.ProtoReflect.Descriptor instead.
func (*UploadBinaryFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{11}
}

func (x *UploadBinaryFileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadBinaryFileRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *UploadBinaryFileRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UploadBinaryFileRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type UploadBinaryFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadBinaryFileResponse) Reset() {
	*x = UploadBinaryFileResponse{}
	mi := &file_proto_keeper_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadBinaryFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadBinaryFileResponse) ProtoMessage() {}

func (x *UploadBinaryFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadBinaryFileResponse.ProtoReflect.Descriptor instead.
func (*UploadBinaryFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{12}
}

type DownloadBinaryFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadBinaryFileRequest) Reset() {
	*x = DownloadBinaryFileRequest{}
	mi := &file_proto_keeper_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadBinaryFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadBinaryFileRequest) ProtoMessage() {}

func (x *DownloadBinaryFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadBinaryFileRequest.ProtoReflect.Descriptor instead.
func (*DownloadBinaryFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{13}
}

func (x *DownloadBinaryFileRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DownloadBinaryFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadBinaryFileResponse) Reset() {
	*x = DownloadBinaryFileResponse{}
	mi := &file_proto_keeper_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadBinaryFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadBinaryFileResponse) ProtoMessage() {}

func (x *DownloadBinaryFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadBinaryFileResponse.ProtoReflect.Descriptor instead.
func (*DownloadBinaryFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{14}
}

func (x *DownloadBinaryFileResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *DownloadBinaryFileResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type UploadTextFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadTextFileRequest) Reset() {
	*x = UploadTextFileRequest{}
	mi := &file_proto_keeper_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadTextFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadTextFileRequest) ProtoMessage() {}

func (x *UploadTextFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadTextFileRequest.ProtoReflect.Descriptor instead.
func (*UploadTextFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{15}
}

func (x *UploadTextFileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadTextFileRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *UploadTextFileRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UploadTextFileRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type UploadTextFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadTextFileResponse) Reset() {
	*x = UploadTextFileResponse{}
	mi := &file_proto_keeper_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadTextFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadTextFileResponse) ProtoMessage() {}

func (x *UploadTextFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadTextFileResponse.ProtoReflect.Descriptor instead.
func (*UploadTextFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{16}
}

type UploadTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadTextRequest) Reset() {
	*x = UploadTextRequest{}
	mi := &file_proto_keeper_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadTextRequest) ProtoMessage() {}

func (x *UploadTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadTextRequest.ProtoReflect.Descriptor instead.
func (*UploadTextRequest) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{17}
}

func (x *UploadTextRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UploadTextRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UploadTextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadTextResponse) Reset() {
	*x = UploadTextResponse{}
	mi := &file_proto_keeper_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadTextResponse) ProtoMessage() {}

func (x *UploadTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadTextResponse.ProtoReflect.Descriptor instead.
func (*UploadTextResponse) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{18}
}

type AddCreditCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        string                 `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Exp           string                 `protobuf:"bytes,2,opt,name=exp,proto3" json:"exp,omitempty"`
	Cvv           string                 `protobuf:"bytes,3,opt,name=cvv,proto3" json:"cvv,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCreditCardRequest) Reset() {
	*x = AddCreditCardRequest{}
	mi := &file_proto_keeper_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCreditCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCreditCardRequest) ProtoMessage() {}

func (x *AddCreditCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCreditCardRequest.ProtoReflect.Descriptor instead.
func (*AddCreditCardRequest) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{19}
}

func (x *AddCreditCardRequest) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *AddCreditCardRequest) GetExp() string {
	if x != nil {
		return x.Exp
	}
	return ""
}

func (x *AddCreditCardRequest) GetCvv() string {
	if x != nil {
		return x.Cvv
	}
	return ""
}

func (x *AddCreditCardRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type AddCreditCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCreditCardResponse) Reset() {
	*x = AddCreditCardResponse{}
	mi := &file_proto_keeper_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCreditCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCreditCardResponse) ProtoMessage() {}

func (x *AddCreditCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCreditCardResponse.ProtoReflect.Descriptor instead.
func (*AddCreditCardResponse) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{20}
}

type CreditCard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        string                 `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Exp           string                 `protobuf:"bytes,2,opt,name=exp,proto3" json:"exp,omitempty"`
	Cvv           string                 `protobuf:"bytes,3,opt,name=cvv,proto3" json:"cvv,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Id            uint32                 `protobuf:"varint,5,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreditCard) Reset() {
	*x = CreditCard{}
	mi := &file_proto_keeper_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditCard) ProtoMessage() {}

func (x *CreditCard) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditCard.ProtoReflect.Descriptor instead.
func (*CreditCard) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{21}
}

func (x *CreditCard) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *CreditCard) GetExp() string {
	if x != nil {
		return x.Exp
	}
	return ""
}

func (x *CreditCard) GetCvv() string {
	if x != nil {
		return x.Cvv
	}
	return ""
}

func (x *CreditCard) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreditCard) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreditCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreditCardRequest) Reset() {
	*x = CreditCardRequest{}
	mi := &file_proto_keeper_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditCardRequest) ProtoMessage() {}

func (x *CreditCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditCardRequest.ProtoReflect.Descriptor instead.
func (*CreditCardRequest) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{22}
}

type CreditCardListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreditCards   []*CreditCard          `protobuf:"bytes,1,rep,name=creditCards,proto3" json:"creditCards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreditCardListResponse) Reset() {
	*x = CreditCardListResponse{}
	mi := &file_proto_keeper_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditCardListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditCardListResponse) ProtoMessage() {}

func (x *CreditCardListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditCardListResponse.ProtoReflect.Descriptor instead.
func (*CreditCardListResponse) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{23}
}

func (x *CreditCardListResponse) GetCreditCards() []*CreditCard {
	if x != nil {
		return x.CreditCards
	}
	return nil
}

type DeleteCreditCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCreditCardRequest) Reset() {
	*x = DeleteCreditCardRequest{}
	mi := &file_proto_keeper_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCreditCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCreditCardRequest) ProtoMessage() {}

func (x *DeleteCreditCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCreditCardRequest.ProtoReflect.Descriptor instead.
func (*DeleteCreditCardRequest) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteCreditCardRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteCreditCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCreditCardResponse) Reset() {
	*x = DeleteCreditCardResponse{}
	mi := &file_proto_keeper_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCreditCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCreditCardResponse) ProtoMessage() {}

func (x *DeleteCreditCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCreditCardResponse.ProtoReflect.Descriptor instead.
func (*DeleteCreditCardResponse) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{25}
}

type BinaryFileListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BinaryFileListRequest) Reset() {
	*x = BinaryFileListRequest{}
	mi := &file_proto_keeper_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinaryFileListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryFileListRequest) ProtoMessage() {}

func (x *BinaryFileListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinaryFileListRequest.ProtoReflect.Descriptor instead.
func (*BinaryFileListRequest) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{26}
}

type BinaryFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id            uint32                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BinaryFile) Reset() {
	*x = BinaryFile{}
	mi := &file_proto_keeper_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinaryFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryFile) ProtoMessage() {}

func (x *BinaryFile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinaryFile.ProtoReflect.Descriptor instead.
func (*BinaryFile) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{27}
}

func (x *BinaryFile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BinaryFile) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BinaryFile) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type BinaryFileListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BinaryFiles   []*BinaryFile          `protobuf:"bytes,1,rep,name=binaryFiles,proto3" json:"binaryFiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BinaryFileListResponse) Reset() {
	*x = BinaryFileListResponse{}
	mi := &file_proto_keeper_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinaryFileListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryFileListResponse) ProtoMessage() {}

func (x *BinaryFileListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinaryFileListResponse.ProtoReflect.Descriptor instead.
func (*BinaryFileListResponse) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{28}
}

func (x *BinaryFileListResponse) GetBinaryFiles() []*BinaryFile {
	if x != nil {
		return x.BinaryFiles
	}
	return nil
}

type UpdateCreditCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          *CreditCard            `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCreditCardRequest) Reset() {
	*x = UpdateCreditCardRequest{}
	mi := &file_proto_keeper_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCreditCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCreditCardRequest) ProtoMessage() {}

func (x *UpdateCreditCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCreditCardRequest.ProtoReflect.Descriptor instead.
func (*UpdateCreditCardRequest) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{29}
}

func (x *UpdateCreditCardRequest) GetCard() *CreditCard {
	if x != nil {
		return x.Card
	}
	return nil
}

type UpdateCreditCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCreditCardResponse) Reset() {
	*x = UpdateCreditCardResponse{}
	mi := &file_proto_keeper_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCreditCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCreditCardResponse) ProtoMessage() {}

func (x *UpdateCreditCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCreditCardResponse.ProtoReflect.Descriptor instead.
func (*UpdateCreditCardResponse) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{30}
}

type UpdateCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credentials   *Credential            `protobuf:"bytes,1,opt,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCredentialsRequest) Reset() {
	*x = UpdateCredentialsRequest{}
	mi := &file_proto_keeper_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCredentialsRequest) ProtoMessage() {}

func (x *UpdateCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCredentialsRequest.ProtoReflect.Descriptor instead.
func (*UpdateCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{31}
}

func (x *UpdateCredentialsRequest) GetCredentials() *Credential {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type UpdateCredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCredentialsResponse) Reset() {
	*x = UpdateCredentialsResponse{}
	mi := &file_proto_keeper_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCredentialsResponse) ProtoMessage() {}

func (x *UpdateCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCredentialsResponse.ProtoReflect.Descriptor instead.
func (*UpdateCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{32}
}

type UpdateBinaryFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Id            uint32                 `protobuf:"varint,5,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBinaryFileRequest) Reset() {
	*x = UpdateBinaryFileRequest{}
	mi := &file_proto_keeper_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBinaryFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBinaryFileRequest) ProtoMessage() {}

func (x *UpdateBinaryFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBinaryFileRequest.ProtoReflect.Descriptor instead.
func (*UpdateBinaryFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{33}
}

func (x *UpdateBinaryFileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UpdateBinaryFileRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *UpdateBinaryFileRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateBinaryFileRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *UpdateBinaryFileRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateBinaryFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBinaryFileResponse) Reset() {
	*x = UpdateBinaryFileResponse{}
	mi := &file_proto_keeper_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBinaryFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBinaryFileResponse) ProtoMessage() {}

func (x *UpdateBinaryFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBinaryFileResponse.ProtoReflect.Descriptor instead.
func (*UpdateBinaryFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{34}
}

type DeleteTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTextRequest) Reset() {
	*x = DeleteTextRequest{}
	mi := &file_proto_keeper_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTextRequest) ProtoMessage() {}

func (x *DeleteTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTextRequest.ProtoReflect.Descriptor instead.
func (*DeleteTextRequest) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{35}
}

func (x *DeleteTextRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteTextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTextResponse) Reset() {
	*x = DeleteTextResponse{}
	mi := &file_proto_keeper_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTextResponse) ProtoMessage() {}

func (x *DeleteTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTextResponse.ProtoReflect.Descriptor instead.
func (*DeleteTextResponse) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{36}
}

type Text struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IdFile        bool                   `protobuf:"varint,2,opt,name=idFile,proto3" json:"idFile,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Filename      string                 `protobuf:"bytes,5,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Text) Reset() {
	*x = Text{}
	mi := &file_proto_keeper_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Text) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Text) ProtoMessage() {}

func (x *Text) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Text.ProtoReflect.Descriptor instead.
func (*Text) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{37}
}

func (x *Text) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Text) GetIdFile() bool {
	if x != nil {
		return x.IdFile
	}
	return false
}

func (x *Text) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Text) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Text) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type UpdateTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTextRequest) Reset() {
	*x = UpdateTextRequest{}
	mi := &file_proto_keeper_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTextRequest) ProtoMessage() {}

func (x *UpdateTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTextRequest.ProtoReflect.Descriptor instead.
func (*UpdateTextRequest) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{38}
}

func (x *UpdateTextRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type TextListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextListRequest) Reset() {
	*x = TextListRequest{}
	mi := &file_proto_keeper_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextListRequest) ProtoMessage() {}

func (x *TextListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextListRequest.ProtoReflect.Descriptor instead.
func (*TextListRequest) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{39}
}

type TextListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          []*Text                `protobuf:"bytes,1,rep,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextListResponse) Reset() {
	*x = TextListResponse{}
	mi := &file_proto_keeper_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextListResponse) ProtoMessage() {}

func (x *TextListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextListResponse.ProtoReflect.Descriptor instead.
func (*TextListResponse) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{40}
}

func (x *TextListResponse) GetInfo() []*Text {
	if x != nil {
		return x.Info
	}
	return nil
}

type UpdateTextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTextResponse) Reset() {
	*x = UpdateTextResponse{}
	mi := &file_proto_keeper_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTextResponse) ProtoMessage() {}

func (x *UpdateTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTextResponse.ProtoReflect.Descriptor instead.
func (*UpdateTextResponse) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{41}
}

type UpdateTextFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Id            uint32                 `protobuf:"varint,5,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTextFileRequest) Reset() {
	*x = UpdateTextFileRequest{}
	mi := &file_proto_keeper_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTextFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTextFileRequest) ProtoMessage() {}

func (x *UpdateTextFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTextFileRequest.ProtoReflect.Descriptor instead.
func (*UpdateTextFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{42}
}

func (x *UpdateTextFileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UpdateTextFileRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *UpdateTextFileRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateTextFileRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *UpdateTextFileRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateTextFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTextFileResponse) Reset() {
	*x = UpdateTextFileResponse{}
	mi := &file_proto_keeper_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTextFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTextFileResponse) ProtoMessage() {}

func (x *UpdateTextFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTextFileResponse.ProtoReflect.Descriptor instead.
func (*UpdateTextFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{43}
}

type DeleteBinaryFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBinaryFileRequest) Reset() {
	*x = DeleteBinaryFileRequest{}
	mi := &file_proto_keeper_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBinaryFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBinaryFileRequest) ProtoMessage() {}

func (x *DeleteBinaryFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBinaryFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteBinaryFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{44}
}

func (x *DeleteBinaryFileRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteBinaryFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBinaryFileResponse) Reset() {
	*x = DeleteBinaryFileResponse{}
	mi := &file_proto_keeper_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBinaryFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBinaryFileResponse) ProtoMessage() {}

func (x *DeleteBinaryFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keeper_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBinaryFileResponse.ProtoReflect.Descriptor instead.
func (*DeleteBinaryFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_keeper_proto_rawDescGZIP(), []int{45}
}

var File_proto_keeper_proto protoreflect.FileDescriptor

const file_proto_keeper_proto_rawDesc = "" +
	"\n" +
	"\x12proto/keeper.proto\x12\fkeeper_proto\"B\n" +
	"\x0eNewUserRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x11\n" +
	"\x0fNewUserResponse\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"%\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"k\n" +
	"\x15AddCredentialsRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\x18\n" +
	"\x16AddCredentialsResponse\"p\n" +
	"\n" +
	"Credential\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\rR\x02id\"\x17\n" +
	"\x15CredentialListRequest\"T\n" +
	"\x16CredentialListResponse\x12:\n" +
	"\vcredentials\x18\x01 \x03(\v2\x18.keeper_proto.CredentialR\vcredentials\")\n" +
	"\x17DeleteCredentialRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\x1a\n" +
	"\x18DeleteCredentialResponse\"\x85\x01\n" +
	"\x17UploadBinaryFileRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\"\x1a\n" +
	"\x18UploadBinaryFileResponse\"+\n" +
	"\x19DownloadBinaryFileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"R\n" +
	"\x1aDownloadBinaryFileResponse\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"\x83\x01\n" +
	"\x15UploadTextFileRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\"\x18\n" +
	"\x16UploadTextFileResponse\"O\n" +
	"\x11UploadTextRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"\x14\n" +
	"\x12UploadTextResponse\"t\n" +
	"\x14AddCreditCardRequest\x12\x16\n" +
	"\x06number\x18\x01 \x01(\tR\x06number\x12\x10\n" +
	"\x03exp\x18\x02 \x01(\tR\x03exp\x12\x10\n" +
	"\x03cvv\x18\x03 \x01(\tR\x03cvv\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\x17\n" +
	"\x15AddCreditCardResponse\"z\n" +
	"\n" +
	"CreditCard\x12\x16\n" +
	"\x06number\x18\x01 \x01(\tR\x06number\x12\x10\n" +
	"\x03exp\x18\x02 \x01(\tR\x03exp\x12\x10\n" +
	"\x03cvv\x18\x03 \x01(\tR\x03cvv\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x0e\n" +
	"\x02id\x18\x05 \x01(\rR\x02id\"\x13\n" +
	"\x11CreditCardRequest\"T\n" +
	"\x16CreditCardListResponse\x12:\n" +
	"\vcreditCards\x18\x01 \x03(\v2\x18.keeper_proto.CreditCardR\vcreditCards\")\n" +
	"\x17DeleteCreditCardRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\x1a\n" +
	"\x18DeleteCreditCardResponse\"\x17\n" +
	"\x15BinaryFileListRequest\"R\n" +
	"\n" +
	"BinaryFile\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\rR\x02id\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"T\n" +
	"\x16BinaryFileListResponse\x12:\n" +
	"\vbinaryFiles\x18\x01 \x03(\v2\x18.keeper_proto.BinaryFileR\vbinaryFiles\"G\n" +
	"\x17UpdateCreditCardRequest\x12,\n" +
	"\x04card\x18\x01 \x01(\v2\x18.keeper_proto.CreditCardR\x04card\"\x1a\n" +
	"\x18UpdateCreditCardResponse\"V\n" +
	"\x18UpdateCredentialsRequest\x12:\n" +
	"\vcredentials\x18\x01 \x01(\v2\x18.keeper_proto.CredentialR\vcredentials\"\x1b\n" +
	"\x19UpdateCredentialsResponse\"\x95\x01\n" +
	"\x17UpdateBinaryFileRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x0e\n" +
	"\x02id\x18\x05 \x01(\rR\x02id\"\x1a\n" +
	"\x18UpdateBinaryFileResponse\"#\n" +
	"\x11DeleteTextRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\x14\n" +
	"\x12DeleteTextResponse\"\x86\x01\n" +
	"\x04Text\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x16\n" +
	"\x06idFile\x18\x02 \x01(\bR\x06idFile\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1a\n" +
	"\bfilename\x18\x05 \x01(\tR\bfilename\"#\n" +
	"\x11UpdateTextRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\x11\n" +
	"\x0fTextListRequest\":\n" +
	"\x10TextListResponse\x12&\n" +
	"\x04info\x18\x01 \x03(\v2\x12.keeper_proto.TextR\x04info\"\x14\n" +
	"\x12UpdateTextResponse\"\x93\x01\n" +
	"\x15UpdateTextFileRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x0e\n" +
	"\x02id\x18\x05 \x01(\rR\x02id\"\x18\n" +
	"\x16UpdateTextFileResponse\")\n" +
	"\x17DeleteBinaryFileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\x1a\n" +
	"\x18DeleteBinaryFileResponse2\x8f\x0f\n" +
	"\x06Keeper\x12K\n" +
	"\fregistration\x12\x1c.keeper_proto.NewUserRequest\x1a\x1d.keeper_proto.NewUserResponse\x12@\n" +
	"\x05login\x12\x1a.keeper_proto.LoginRequest\x1a\x1b.keeper_proto.LoginResponse\x12[\n" +
	"\x0eaddCredentials\x12#.keeper_proto.AddCredentialsRequest\x1a$.keeper_proto.AddCredentialsResponse\x12_\n" +
	"\x12getCredentialsList\x12#.keeper_proto.CredentialListRequest\x1a$.keeper_proto.CredentialListResponse\x12a\n" +
	"\x10deleteCredential\x12%.keeper_proto.DeleteCredentialRequest\x1a&.keeper_proto.DeleteCredentialResponse\x12d\n" +
	"\x11updateCredentials\x12&.keeper_proto.UpdateCredentialsRequest\x1a'.keeper_proto.UpdateCredentialsResponse\x12c\n" +
	"\x10uploadBinaryFile\x12%.keeper_proto.UploadBinaryFileRequest\x1a&.keeper_proto.UploadBinaryFileResponse(\x01\x12^\n" +
	"\x11getBinaryFileList\x12#.keeper_proto.BinaryFileListRequest\x1a$.keeper_proto.BinaryFileListResponse\x12i\n" +
	"\x12downloadBinaryFile\x12'.keeper_proto.DownloadBinaryFileRequest\x1a(.keeper_proto.DownloadBinaryFileResponse0\x01\x12c\n" +
	"\x10updateBinaryFile\x12%.keeper_proto.UpdateBinaryFileRequest\x1a&.keeper_proto.UpdateBinaryFileResponse(\x01\x12a\n" +
	"\x10deleteBinaryFile\x12%.keeper_proto.DeleteBinaryFileRequest\x1a&.keeper_proto.DeleteBinaryFileResponse\x12]\n" +
	"\x0euploadTextFile\x12#.keeper_proto.UploadTextFileRequest\x1a$.keeper_proto.UploadTextFileResponse(\x01\x12L\n" +
	"\vgetTextList\x12\x1d.keeper_proto.TextListRequest\x1a\x1e.keeper_proto.TextListResponse\x12O\n" +
	"\n" +
	"uploadText\x12\x1f.keeper_proto.UploadTextRequest\x1a .keeper_proto.UploadTextResponse\x12O\n" +
	"\n" +
	"deleteText\x12\x1f.keeper_proto.DeleteTextRequest\x1a .keeper_proto.DeleteTextResponse\x12O\n" +
	"\n" +
	"updateText\x12\x1f.keeper_proto.UpdateTextRequest\x1a .keeper_proto.UpdateTextResponse\x12[\n" +
	"\x0eupdateTextFile\x12#.keeper_proto.UpdateTextFileRequest\x1a$.keeper_proto.UpdateTextFileResponse\x12X\n" +
	"\raddCreditCard\x12\".keeper_proto.AddCreditCardRequest\x1a#.keeper_proto.AddCreditCardResponse\x12Z\n" +
	"\x11getCreditCardList\x12\x1f.keeper_proto.CreditCardRequest\x1a$.keeper_proto.CreditCardListResponse\x12a\n" +
	"\x10updateCreditCard\x12%.keeper_proto.UpdateCreditCardRequest\x1a&.keeper_proto.UpdateCreditCardResponse\x12a\n" +
	"\x10deleteCreditCard\x12%.keeper_proto.DeleteCreditCardRequest\x1a&.keeper_proto.DeleteCreditCardResponseB\x0eZ\fproto/keeperb\x06proto3"

var (
	file_proto_keeper_proto_rawDescOnce sync.Once
	file_proto_keeper_proto_rawDescData []byte
)

func file_proto_keeper_proto_rawDescGZIP() []byte {
	file_proto_keeper_proto_rawDescOnce.Do(func() {
		file_proto_keeper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_keeper_proto_rawDesc), len(file_proto_keeper_proto_rawDesc)))
	})
	return file_proto_keeper_proto_rawDescData
}

var file_proto_keeper_proto_msgTypes = make([]protoimpl.MessageInfo, 46)
var file_proto_keeper_proto_goTypes = []any{
	(*NewUserRequest)(nil),             // 0: keeper_proto.NewUserRequest
	(*NewUserResponse)(nil),            // 1: keeper_proto.NewUserResponse
	(*LoginRequest)(nil),               // 2: keeper_proto.LoginRequest
	(*LoginResponse)(nil),              // 3: keeper_proto.LoginResponse
	(*AddCredentialsRequest)(nil),      // 4: keeper_proto.AddCredentialsRequest
	(*AddCredentialsResponse)(nil),     // 5: keeper_proto.AddCredentialsResponse
	(*Credential)(nil),                 // 6: keeper_proto.Credential
	(*CredentialListRequest)(nil),      // 7: keeper_proto.CredentialListRequest
	(*CredentialListResponse)(nil),     // 8: keeper_proto.CredentialListResponse
	(*DeleteCredentialRequest)(nil),    // 9: keeper_proto.DeleteCredentialRequest
	(*DeleteCredentialResponse)(nil),   // 10: keeper_proto.DeleteCredentialResponse
	(*UploadBinaryFileRequest)(nil),    // 11: keeper_proto.UploadBinaryFileRequest
	(*UploadBinaryFileResponse)(nil),   // 12: keeper_proto.UploadBinaryFileResponse
	(*DownloadBinaryFileRequest)(nil),  // 13: keeper_proto.DownloadBinaryFileRequest
	(*DownloadBinaryFileResponse)(nil), // 14: keeper_proto.DownloadBinaryFileResponse
	(*UploadTextFileRequest)(nil),      // 15: keeper_proto.UploadTextFileRequest
	(*UploadTextFileResponse)(nil),     // 16: keeper_proto.UploadTextFileResponse
	(*UploadTextRequest)(nil),          // 17: keeper_proto.UploadTextRequest
	(*UploadTextResponse)(nil),         // 18: keeper_proto.UploadTextResponse
	(*AddCreditCardRequest)(nil),       // 19: keeper_proto.AddCreditCardRequest
	(*AddCreditCardResponse)(nil),      // 20: keeper_proto.AddCreditCardResponse
	(*CreditCard)(nil),                 // 21: keeper_proto.CreditCard
	(*CreditCardRequest)(nil),          // 22: keeper_proto.CreditCardRequest
	(*CreditCardListResponse)(nil),     // 23: keeper_proto.CreditCardListResponse
	(*DeleteCreditCardRequest)(nil),    // 24: keeper_proto.DeleteCreditCardRequest
	(*DeleteCreditCardResponse)(nil),   // 25: keeper_proto.DeleteCreditCardResponse
	(*BinaryFileListRequest)(nil),      // 26: keeper_proto.BinaryFileListRequest
	(*BinaryFile)(nil),                 // 27: keeper_proto.BinaryFile
	(*BinaryFileListResponse)(nil),     // 28: keeper_proto.BinaryFileListResponse
	(*UpdateCreditCardRequest)(nil),    // 29: keeper_proto.UpdateCreditCardRequest
	(*UpdateCreditCardResponse)(nil),   // 30: keeper_proto.UpdateCreditCardResponse
	(*UpdateCredentialsRequest)(nil),   // 31: keeper_proto.UpdateCredentialsRequest
	(*UpdateCredentialsResponse)(nil),  // 32: keeper_proto.UpdateCredentialsResponse
	(*UpdateBinaryFileRequest)(nil),    // 33: keeper_proto.UpdateBinaryFileRequest
	(*UpdateBinaryFileResponse)(nil),   // 34: keeper_proto.UpdateBinaryFileResponse
	(*DeleteTextRequest)(nil),          // 35: keeper_proto.DeleteTextRequest
	(*DeleteTextResponse)(nil),         // 36: keeper_proto.DeleteTextResponse
	(*Text)(nil),                       // 37: keeper_proto.Text
	(*UpdateTextRequest)(nil),          // 38: keeper_proto.UpdateTextRequest
	(*TextListRequest)(nil),            // 39: keeper_proto.TextListRequest
	(*TextListResponse)(nil),           // 40: keeper_proto.TextListResponse
	(*UpdateTextResponse)(nil),         // 41: keeper_proto.UpdateTextResponse
	(*UpdateTextFileRequest)(nil),      // 42: keeper_proto.UpdateTextFileRequest
	(*UpdateTextFileResponse)(nil),     // 43: keeper_proto.UpdateTextFileResponse
	(*DeleteBinaryFileRequest)(nil),    // 44: keeper_proto.DeleteBinaryFileRequest
	(*DeleteBinaryFileResponse)(nil),   // 45: keeper_proto.DeleteBinaryFileResponse
}
var file_proto_keeper_proto_depIdxs = []int32{
	6,  // 0: keeper_proto.CredentialListResponse.credentials:type_name -> keeper_proto.Credential
	21, // 1: keeper_proto.CreditCardListResponse.creditCards:type_name -> keeper_proto.CreditCard
	27, // 2: keeper_proto.BinaryFileListResponse.binaryFiles:type_name -> keeper_proto.BinaryFile
	21, // 3: keeper_proto.UpdateCreditCardRequest.card:type_name -> keeper_proto.CreditCard
	6,  // 4: keeper_proto.UpdateCredentialsRequest.credentials:type_name -> keeper_proto.Credential
	37, // 5: keeper_proto.TextListResponse.info:type_name -> keeper_proto.Text
	0,  // 6: keeper_proto.Keeper.registration:input_type -> keeper_proto.NewUserRequest
	2,  // 7: keeper_proto.Keeper.login:input_type -> keeper_proto.LoginRequest
	4,  // 8: keeper_proto.Keeper.addCredentials:input_type -> keeper_proto.AddCredentialsRequest
	7,  // 9: keeper_proto.Keeper.getCredentialsList:input_type -> keeper_proto.CredentialListRequest
	9,  // 10: keeper_proto.Keeper.deleteCredential:input_type -> keeper_proto.DeleteCredentialRequest
	31, // 11: keeper_proto.Keeper.updateCredentials:input_type -> keeper_proto.UpdateCredentialsRequest
	11, // 12: keeper_proto.Keeper.uploadBinaryFile:input_type -> keeper_proto.UploadBinaryFileRequest
	26, // 13: keeper_proto.Keeper.getBinaryFileList:input_type -> keeper_proto.BinaryFileListRequest
	13, // 14: keeper_proto.Keeper.downloadBinaryFile:input_type -> keeper_proto.DownloadBinaryFileRequest
	33, // 15: keeper_proto.Keeper.updateBinaryFile:input_type -> keeper_proto.UpdateBinaryFileRequest
	44, // 16: keeper_proto.Keeper.deleteBinaryFile:input_type -> keeper_proto.DeleteBinaryFileRequest
	15, // 17: keeper_proto.Keeper.uploadTextFile:input_type -> keeper_proto.UploadTextFileRequest
	39, // 18: keeper_proto.Keeper.getTextList:input_type -> keeper_proto.TextListRequest
	17, // 19: keeper_proto.Keeper.uploadText:input_type -> keeper_proto.UploadTextRequest
	35, // 20: keeper_proto.Keeper.deleteText:input_type -> keeper_proto.DeleteTextRequest
	38, // 21: keeper_proto.Keeper.updateText:input_type -> keeper_proto.UpdateTextRequest
	42, // 22: keeper_proto.Keeper.updateTextFile:input_type -> keeper_proto.UpdateTextFileRequest
	19, // 23: keeper_proto.Keeper.addCreditCard:input_type -> keeper_proto.AddCreditCardRequest
	22, // 24: keeper_proto.Keeper.getCreditCardList:input_type -> keeper_proto.CreditCardRequest
	29, // 25: keeper_proto.Keeper.updateCreditCard:input_type -> keeper_proto.UpdateCreditCardRequest
	24, // 26: keeper_proto.Keeper.deleteCreditCard:input_type -> keeper_proto.DeleteCreditCardRequest
	1,  // 27: keeper_proto.Keeper.registration:output_type -> keeper_proto.NewUserResponse
	3,  // 28: keeper_proto.Keeper.login:output_type -> keeper_proto.LoginResponse
	5,  // 29: keeper_proto.Keeper.addCredentials:output_type -> keeper_proto.AddCredentialsResponse
	8,  // 30: keeper_proto.Keeper.getCredentialsList:output_type -> keeper_proto.CredentialListResponse
	10, // 31: keeper_proto.Keeper.deleteCredential:output_type -> keeper_proto.DeleteCredentialResponse
	32, // 32: keeper_proto.Keeper.updateCredentials:output_type -> keeper_proto.UpdateCredentialsResponse
	12, // 33: keeper_proto.Keeper.uploadBinaryFile:output_type -> keeper_proto.UploadBinaryFileResponse
	28, // 34: keeper_proto.Keeper.getBinaryFileList:output_type -> keeper_proto.BinaryFileListResponse
	14, // 35: keeper_proto.Keeper.downloadBinaryFile:output_type -> keeper_proto.DownloadBinaryFileResponse
	34, // 36: keeper_proto.Keeper.updateBinaryFile:output_type -> keeper_proto.UpdateBinaryFileResponse
	45, // 37: keeper_proto.Keeper.deleteBinaryFile:output_type -> keeper_proto.DeleteBinaryFileResponse
	16, // 38: keeper_proto.Keeper.uploadTextFile:output_type -> keeper_proto.UploadTextFileResponse
	40, // 39: keeper_proto.Keeper.getTextList:output_type -> keeper_proto.TextListResponse
	18, // 40: keeper_proto.Keeper.uploadText:output_type -> keeper_proto.UploadTextResponse
	36, // 41: keeper_proto.Keeper.deleteText:output_type -> keeper_proto.DeleteTextResponse
	41, // 42: keeper_proto.Keeper.updateText:output_type -> keeper_proto.UpdateTextResponse
	43, // 43: keeper_proto.Keeper.updateTextFile:output_type -> keeper_proto.UpdateTextFileResponse
	20, // 44: keeper_proto.Keeper.addCreditCard:output_type -> keeper_proto.AddCreditCardResponse
	23, // 45: keeper_proto.Keeper.getCreditCardList:output_type -> keeper_proto.CreditCardListResponse
	30, // 46: keeper_proto.Keeper.updateCreditCard:output_type -> keeper_proto.UpdateCreditCardResponse
	25, // 47: keeper_proto.Keeper.deleteCreditCard:output_type -> keeper_proto.DeleteCreditCardResponse
	27, // [27:48] is the sub-list for method output_type
	6,  // [6:27] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_keeper_proto_init() }
func file_proto_keeper_proto_init() {
	if File_proto_keeper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_keeper_proto_rawDesc), len(file_proto_keeper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   46,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_keeper_proto_goTypes,
		DependencyIndexes: file_proto_keeper_proto_depIdxs,
		MessageInfos:      file_proto_keeper_proto_msgTypes,
	}.Build()
	File_proto_keeper_proto = out.File
	file_proto_keeper_proto_goTypes = nil
	file_proto_keeper_proto_depIdxs = nil
}
